#!/bin/bash

# install nixos from USB stick

# boot into root
nix-channel --add https://nixos.org/channels/nixos-19.03 nixos
curl -fsSL https://raw.githubusercontent.com/massemanet/dotfiles.nixos/master/install/configuration.nix > /etc/nixos/configuration.nix
nixos-rebuild switch --upgrade

# boot in as user

## get ssh keys

# get my stuff
[ ! -e ~/.git ] &&
    cd /tmp && \
	rm -rf dotfiles.nixos && \
	git clone https://github.com/massemanet/dotfiles.nixos && \
	cd dotfiles.nixos && \
	git remote set-url origin git@github.com:massemanet/dotfiles.nixos && \
	mv /tmp/dotfiles.nixos/.git ~
(cd && git reset --hard)

~/bin/install.sh aws-vault
~/bin/install.sh awscli
~/bin/install.sh bazel 0.19
~/bin/install.sh docker
~/bin/install.sh docker-compose
~/bin/install.sh erlang
~/bin/install.sh java
~/bin/install.sh keybase
~/bin/install.sh pgadmin
~/bin/install.sh python

# emacs (cask)
[ ! -d ~/.cask ] && \
    curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
(cd ~/.emacs.d && ~/.cask/bin/cask install)

# edit /etc/default/nodm to have these lines
# NODM_ENABLED=true
# NODM_USER=masse
# NODM_XSESSION=/home/masse/.xsession

# set up lid event
# /etc/acpi/events/lidevent
# event=button/lid
# action=/etc/acpi/lidevent.sh "%e"

# /etc/acpi/lidevent.sh
# #!/bin/bash
# for f in /home/*/bin/lidevent.sh
# do if [ -x "$f" ]
#    then su $(stat -c "%U" $f) -c "$f $1"
#    fi
# done

# let systemd resolve
# /etc/resolv.conf -> /run/systemd/resolve/resolv.conf
# tell systemd resolver to use google
# /etc/systemd/resolved.conf
# [Resolve]
# DNS=8.8.8.8
