#!/bin/bash

# boot into installer
# set up the disk (efi boot, 8G swap, full disk encryption, LVM)
## see e.g. https://gist.github.com/martijnvermaat/76f2e24d0239470dd71050358b4d5134

# set up wifi
wpa_passphrase "Wifi network SSID" "Wifi password" > /etc/wpa_supplicant.conf
systemctl restart wpa_supplicant.service

cat > /dev/null <<EOF
$ gdisk /dev/sda
    o (create new empty partition table)
    n (add partition, 500M, type ef00 EFI)
    n (add partition, remaining space, type 8300 Linux LVM)
    w (write partition table and exit)
$ cryptsetup luksFormat /dev/sda2
$ cryptsetup luksOpen /dev/sda2 enc-pv
$ pvcreate /dev/mapper/enc-pv
$ vgcreate vg /dev/mapper/enc-pv
$ lvcreate -L 8G -n swap vg
$ lvcreate -l '100%FREE' -n root vg
$ mkfs.fat /dev/sda1
$ mkfs.ext4 -L root /dev/vg/root
$ mkswap -L swap /dev/vg/swap
$ mount /dev/vg/root /mnt
$ mkdir /mnt/boot
$ mount /dev/sda1 /mnt/boot
$ swapon /dev/vg/swap
EOF

# generate hw description
nixos-generate-config --root /mnt

# get config from github
URL=https://raw.githubusercontent.com/massemanet/dotfiles.nixos
curl "$URL/master/install/configuration.nix" > /mnt/etc/nixos/configuration.nix

# in '/mnt/etc/nixos/configuration.nix', you must;
# edit the name of the root lvm partition, e.g.
#     device = "/dev/nvme0n1p2";
# and the hostname, e.g.
#     networking.hostName = "dysmorphic";

# install
nixos-install

# reboot
reboot now

# log in as root; set the user password
passwd masse

# log in as user
## get ssh keys
mkdir -p ~/.ssh
scp massema.net:~/.ssh/id_rsa ~/.ssh/
scp massema.net:~/.ssh/id_rsa.pub ~/.ssh/

## get my stuff
[ ! -e ~/.git ] &&
    cd /tmp && \
        rm -rf dotfiles.nixos && \
        git clone https://github.com/massemanet/dotfiles.nixos && \
        cd dotfiles.nixos && \
        git remote set-url origin git@github.com:massemanet/dotfiles.nixos && \
        mv /tmp/dotfiles.nixos/.git ~
(cd && git reset --hard)

## keep nix conf in ~ so we can git control
sudo rm  /etc/nixos/configuration.nix && \
    sudo ln -s ~/install/configuration.nix /etc/nixos/
